apiVersion : apps/v1
kind: Deployment
metadata:
  name: sugnanikubernetes 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sugnanikubernetes
  template:
    metadata:
      labels:
        app: sugnanikubernetes 
    spec:
      containers:
        - name: sugnanikubernetes 
          image: ntsregistry.azurecr.io/sugnanikubernetes
          ports:
          - containerPort: 8080